<html><body link="#FE9900" alink="#FE9900" vlink="#FE9900"><table width="439" cellpadding="10" cellspacing="0"><tr><td align="center" style="padding:0;border-bottom:1px dotted #66C029"><p><a href="http://www.woophy.com"><img src="http://www.woophy.com/images/woophy_logo.gif" border="0"></a></p></td></tr>
<tr><td style="padding:10px 10px;border-bottom:1px dotted #66C029"><b><font size="2" face="georgia,arial,helvetica,sans" color="#003900">Lettre de bienvenue {date}</font></b></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Bienvenue sur Woophy </b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_371509.jpg" alt="" title="" /></p>Bonjour, {user_name}, et merci de rejoindre Woophy, une communauté amicale de plus de 40.000 photographes amateurs, dont le but est de créer une collection accessible, visuelle et actuelle, composée d'une base de données décrivant notre remarquable monde et ses diversités, tant culturelles que géographiques.<br />
<br />
Pour faciliter votre navigation sur le site, nous avons préparé cette lettre avec quelques trucs et astuces pour trouver votre chemin sur Woophy. Inutile de tout lire en une fois mais elle vous sera sûrement utile à l'occasion! Des questions? Prenez le temps de découvrir toutes les fonctions de Woophy, jetez un coup d'oeil sur Woophy <b><a href="http://www.woophy.com/faq" target="_blank" rel="nofollow">FAQ</a></b> et n'hésitez pas à contacter votre ambassadeur Woophy (liste ci-dessous). De plus, vous trouverez toujours quelqu'un sur le <b><a href="http://www.woophy.com/forum" target="_blank" rel="nofollow">forum</a></b> pour vous aider.<br />
<br />
photo: <b><a href="http://www.woophy.com/member/ewest/photos?&amp;order_by=rating" target="_blank" rel="nofollow">ewest</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Trucs et astuces</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_657561.jpg" alt="" title="" /></p>Maintenant que vous avez rejoint Woophy, nous attendons que vous postiez vos plus belles photos. Si vous avez plusieurs photos qui, ensemble, racontent une histoire, pourquoi n'écririez vous pas un <b><a href="http://www.woophy.com/member/?blogs" target="_blank" rel="nofollow">blog</a></b>?<br />
Vous verrez vite que d'autres regarderont vos photos, les commenteront et même les noteront.<br />Vous pouvez en faire autant.<br />En notant les photos (sur une échelle de 1 à 5 étoiles *), vous aidez la communauté à trouver plus rapidement les meilleures photos ou les plus intéressantes.<br />Poster des commentaires constructifs peut aider. Bien sûr, ce n'est pas un travail facile mais essayez de prendre un peu de temps et de dire ce que vous aimez et/ou ce que vous n'aimez pas sur une photo. Recevoir des commentaires honnêtes et constructifs peut vous aider à améliorer votre approche photographique.<br />
<br />
 Woophy propose également un forum avec de nombreux thèmes. N'hésitez pas à les consulter en cliquant sur l'onglet <b><a href="http://www.woophy.com/forum" target="_blank" rel="nofollow">&quot;forum&quot;</a></b> et, pourquoi pas?, à ouvrir vous-même un nouveau thème de discussion.<br />
<br />
photo: <b><a href="http://www.woophy.com/member/Richt/photos?&amp;order_by=rating" target="_blank" rel="nofollow">Richt</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>A faire et à ne pas faire</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_689481.jpg" alt="" title="" /></p>Merci de partager vos photos avec nous. Toutes les photos sont bienvenues, surtout celles qui représentent un endroit, montrent à quoi il ressemble et comment on y vit. Merci de ne pas utiliser des modifications numériques excessives (des corrections modérées de contraste ou couleurs suffisent), de grosses inscriptions (une discrète signature sera parfaite) ou des bordures trop lourdes.<br />
<br />Ne postez ni publicité, ni pornographie, ni propagande politique, ni images violentes ni des photos dont vous n'êtes pas l'auteur.<br />Ceci est illégal et nous ne voulons pas le cautionner ni avoir à sévir en clôturant votre compte sur Woophy.<br />
<br />Ceux qui regardent vos photos voudront peut être en savoir un peu plus! Ajoutez donc titres et descriptions. Quelques mots-clé feront apparaître votre photo quand une recherche spécifique est lancée (par exemple: <b><a href="http://www.woophy.com/map#&amp;key=keywords&amp;val=glacier" target="_blank" rel="nofollow">glacier</a></b>. Essayez!)<br />
<br />Merci de regarder les photos des autres membres de Woophy! Nous vous suggérons de le faire à partir de la page &quot;carte&quot; (&quot;map&quot; sur le site).<br />Vous pouvez aussi sélectionner vos photos et/ou photographes favoris. Vous pouvez également discuter et poser des questions à travers vos commentaires - voire même donner des notes.<br />
<br />Beaucoup de membres apprécient les critiques mais veillez à rester honnête et constructif. Ne vous sentez pas obligé de répondre aux commentaires reçus.<br />
<br />
photo: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=38.60768&amp;lmt=0&amp;lng=44.335213&amp;mag=2.290768&amp;val=rik%20herrygers" target="_blank" rel="nofollow">Rik Herrygers</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Les &quot;ambassadeurs&quot;</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_99924.jpg" alt="" title="" /></p>L'Anglais est la langue utilisée sur Woophy mais, pour chaque pays, vous trouverez un contact appelé &quot;Woophy Ambassador&quot; qui se fera un plaisir de répondre dans votre langue à toute question que vous pourriez vous poser.<br />
<br />
Vous pouvez trouver l'ambassadeur de votre pays sur la page <b><a href="http://www.woophy.com/member/?ambassadors" target="_blank" rel="nofollow">ambassadeurs</a></b>. De là, vous pouvez lui envoyer un e-mail dans votre langue.<br />
<br />
photo: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=14.058445&amp;lmt=0&amp;lng=-85.140706&amp;mag=14.668508&amp;val=cande" target="_blank" rel="nofollow">Cande</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Donations</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_82984.jpg" alt="" title="" /></p>Soutenez Woophy en achetant le T-shirt original <b><a href="http://www.woophy.com/donate" target="_blank" rel="nofollow">Genuine Woophy T-shirt</a></b>. Les fonds collectés par la vente de ce T-shirt sont investis dans Woophy. Si vous ne désirez pas acheter le T-shirt mais souhaitez aider Woophy, vous pouvez également faire une <b><a href="http://www.woophy.com/donate" target="_blank" rel="nofollow">donation</a></b>. <br />
<br />
photo: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=11.214494&amp;lmt=0&amp;lng=51.691361&amp;mag=3.337679&amp;val=Hes%20van%20Huizen" target="_blank" rel="nofollow">Hes van Huizen</a></b></font></td></tr>
<tr><td align="center"><p><a href="http://www.woophy.com"><img src="http://www.woophy.com/images/woophy_symbol.gif" border="0"></a></p></td></tr></table></body></html>
