<html><body link="#FE9900" alink="#FE9900" vlink="#FE9900"><table width="439" cellpadding="10" cellspacing="0"><tr><td align="center" style="padding:0;border-bottom:1px dotted #66C029"><p><a href="http://www.woophy.com"><img src="http://www.woophy.com/images/woophy_logo.gif" border="0"></a></p></td></tr>
<tr><td style="padding:10px 10px;border-bottom:1px dotted #66C029"><b><font size="2" face="georgia,arial,helvetica,sans" color="#003900">Välkomstbrev {date}</font></b></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Välkommen till Woophy</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_371509.jpg" alt="" title="" /></p>Hej {user_name}, tack för att du går med i Woophy, den goda gemenskapen med över 40.000 amatörfotografer, som med ett demokratiskt och kollektivt arbete försöker skapa en lättillgänglig och färsk databas med bilder av vår fantastiska värld.<br />
<br />
För en enkel start har vi i detta nyhetsbrev samlat några tips och trix för att hitta runt Woophy. Du behöver inte läsa allt på en gång, men du kan använda detta för framtida referens.<br />
<br />
Har du frågor? Ta god tid på dig att upptäcka alla Woophys funktioner. Ta en titt på Woophys <b><a href="http://www.woophy.com/faq" target="_blank" rel="nofollow">&quot;Vanliga frågor&quot;</a></b> (Woophy FAQ) och tveka inte att fråga din Woophy ambassadör (se nedan). Och du kommer alltid att hitta någon som kan hjälpa dig i <b><a href="http://www.woophy.com/forum" target="_blank" rel="nofollow">forumet</a></b> (forum).<br />
<br />
foto: <b><a href="http://www.woophy.com/member/ewest/photos?&amp;order_by=rating" target="_blank" rel="nofollow">ewest</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Tips och trix</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_657561.jpg" alt="" title="" /></p>Nu när du gått med i Woophy, väntar vi oss att du ska visa dina bästa bilder. Om du har flera bilder som tillsammans berättar en historia, varför inte skriva en <b><a href="http://www.woophy.com/member/?blogs" target="_blank" rel="nofollow">blogg</a></b>?<br />
Notera att blogger, kommentarer/beskrivningar på dina foton samt kommernarer på andras foton skall vara på engelska, Korta meningar eller några ord räcker bra.<br />
<br />
Du kommer snart att inse att andra människor kommer att ta en titt på dina bilder, dom kommer dessutom att betygssätta och kommentera dom. Du är också välkommen att betygsätta och kommentera andras bilder.<br />
<br />
Genom att sätta betyg (med en skala på en till fem stjärnor) kan du hjälpa vår grupp att hitta de bästa eller mest intressanta bilderna först.<br />
<br />
Du kan hjälpa till genom att lämna en meningsfull kommentar om andras foton. Detta kanske inte är så lätt, men ta lite tid på dig och försök att skriva vad du tycker om eller inte tycker om ett foto. Att få ärliga och konstruktiva synpunkter på dina bilder kan hjälpa dig att förbättra din fotografering.<br />
<br />
Woophy har också ett <b><a href="http://www.woophy.com/forum" target="_blank" rel="nofollow">forum</a></b> med en hel del olika ämnen. Tveka inte att ta en titt på länkarna genom att välja forumfliken. Där hittar du en lista över de pågående diskussionerna. Om du vill ta upp ett nytt ämne kan du öppna en egen tråd.<br />
<br />
foto: <b><a href="http://www.woophy.com/member/Richt/photos?&amp;order_by=rating" target="_blank" rel="nofollow">Richt</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Regler och förbud</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_689481.jpg" alt="" title="" /></p>Vi uppskattar om du delar med dig dina bilder av världen. Alla bilder är välkomna, särskilt de som ger ett intryck av en plats, hur det ser ut och känns. Gör inte alltför stora digitala förändringar (lite kontrast och färgkorrigering är bra), &quot;overlay&quot; med stora bokstäver (ett litet meddelande om upphovsrätt är ok) och inga iögonfallande ramar.<br />
<br />
Lägg inte in reklam, porr, politisk propaganda, blodiga/hämska bilder och bilder som inte är dina. Detta är olagligt och vi vill ogärna stänga ditt Woopy konto.<br />
<br />
De som tittar på dina foton vill kanske veta lite mer om dom! Så lägg informativa rubriker och beskrivningar. Vissa meningsfulla sökord gör att din bild visas när någon söker efter något specifikt. Här är bara ett exempel, <b><a href="http://www.woophy.com/map#&amp;key=keywords&amp;val=glacier" target="_blank" rel="nofollow">&quot;glacier&quot;</a></b> (glaciär). Prova själv!<br />
<br />
Ta en titt på andra Woophy-användares bilder! Klicka på en intressant plats på världskartan (Map) och hitta bilder från intressanta platser. Du kan också välja favoriter bland medlemmarna och poängsätta bilder som du tycker om. Du kan kommentera och ställa frågor genom att skicka en kommentar till deras bilder - och även poängsätta dem. Många medlemmar uppskattar omdömen om sina bilder, men det skall vara rättvist och konstruktivt. Känn dig inte tvungen att svara på kommentarerna. <br />
<br />
foto: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=38.60768&amp;lmt=0&amp;lng=44.335213&amp;mag=2.290768&amp;val=rik%20herrygers" target="_blank" rel="nofollow">Rik Herrygers</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Ambassadörerna</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_99924.jpg" alt="" title="" /></p>Språket I Woophy är engelska, men för varje land finns en kontaktperson, som kallas Woophy-ambassadör. Han/hon hjälper dig gärna med frågor du kan ha - på ditt eget språk.<br />
<br />
Du hittar Woophyambassadören för ditt land på <b><a href="http://www.woophy.com/member/?ambassadors" target="_blank" rel="nofollow">Ambassadörssidan</a></b> (Ambassadors). Härifrån kan du sända honom eller henne ett email på ditt eget språk.<br />
<br />
foto: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=14.058445&amp;lmt=0&amp;lng=-85.140706&amp;mag=14.668508&amp;val=cande" target="_blank" rel="nofollow">Cande</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Donera</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_82984.jpg" alt="" title="" /></p>Stöd Woophy genom att köpa en äkta <b><a href="http://www.woophy.com/donate" target="_blank" rel="nofollow">Woophy T-shirt</a></b> (Genuine Woophy T-shirt). Alla pengar som kommer in genom försäljning av denna T-shirt kommer att investeras i Woophy. Om du inte vill köpa en t-shirt, men skulle vilja stödja Woophy ändå kan du alltid göra en <b><a href="http://www.woophy.com/donate" target="_blank" rel="nofollow">donation</a></b>.<br />
<br />
foto: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=11.214494&amp;lmt=0&amp;lng=51.691361&amp;mag=3.337679&amp;val=Hes%20van%20Huizen" target="_blank" rel="nofollow">Hes van Huizen</a></b></font></td></tr>
<tr><td align="center"><p><a href="http://www.woophy.com"><img src="http://www.woophy.com/images/woophy_symbol.gif" border="0"></a></p></td></tr></table></body></html>