<html><body link="#FE9900" alink="#FE9900" vlink="#FE9900"><table width="439" cellpadding="10" cellspacing="0"><tr><td align="center" style="padding:0;border-bottom:1px dotted #66C029"><p><a href="http://www.woophy.com"><img src="http://www.woophy.com/images/woophy_logo.gif" border="0"></a></p></td></tr>
<tr><td style="padding:10px 10px;border-bottom:1px dotted #66C029"><b><font size="2" face="georgia,arial,helvetica,sans" color="#003900">Welcome Letter {date}</font></b></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Welcome to Woophy</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_371509.jpg" alt="" title="" /></p>Hello {user_name}, thank you for joining woophy, the friendly community of over 40,000 amateur photographers, trying to create an accessible, visual, current, democratic and collective work of art comprised of a database picturing our remarkable world.<br />
<br />
For an easy start we have compiled this newsletter with a few tips and tricks to find your way around Woophy. You don&#039;t have to read it all at once, but you might want to keep it for further reference.
Any questions? Take your time to discover all of woophy&#039;s functions. Have a look at the Woophy <b><a href="http://www.woophy.com/faq" target="_blank" rel="nofollow">FAQ</a></b> and please don&#039;t hesitate to ask your Woophy ambassador (see below). And you will always find someone to help you in the <b><a href="http://www.woophy.com/forum" target="_blank" rel="nofollow">forum</a></b>. <br />
<br />
photo: <b><a href="http://www.woophy.com/member/ewest/photos?&amp;order_by=rating" target="_blank" rel="nofollow">ewest</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Tips and tricks</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_657561.jpg" alt="" title="" /></p>Now that you joined Woophy, we are waiting for you to show us your best photos. If you have several photos that altogether tell a story, why not write a <b><a href="http://www.woophy.com/member/?blogs" target="_blank" rel="nofollow">blog</a></b>?<br />
<br />
You will soon recognize, that other people will have a look at your photos, they even rate and comment them. You are welcome to rate and comment other photos as well.<br />
<br />
By rating (on a scale form one star to five stars) you can help the community to find the best or most interesting photos first.<br />
<br />
You can help by leaving a meaningful comment about his photo. This might not be an easy task, but try to take some time and write what you like and/or don&#039;t like about a photo. Getting honest and constructive comments on your photos may help you to improve your photography.<br />
<br />
Woophy also provides a <b><a href="http://www.woophy.com/forum" target="_blank" rel="nofollow">forum</a></b> with a whole lot of different topics. Don&#039;t hesitate to take a look at the threads by choosing the forum tab. You will find a list of the current discussions. If you want to talk about a new topic you can open your own thread.<br />
<br />
photo: <b><a href="http://www.woophy.com/member/Richt/photos?&amp;order_by=rating" target="_blank" rel="nofollow">Richt</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Do&#039;s and don&#039;ts</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_689481.jpg" alt="" title="" /></p>Please do share your photos of the world with us. All photos are welcome, especially those that give an impression of a place, how it looks and feels. Please don&#039;t use excessive digital alterations (a bit of contrast and color correction is fine), large text overlays (a small copyright notice is o.k.) and oppressive borders.<br />
<br />
Don&#039;t upload advertisements, porn, political propaganda, gory images and photos that aren&#039;t yours. This is illegal and we don&#039;t want to unlock our mean Woophy account cruncher.<br />
<br />
Your viewers may want to know a bit about your photo! So add informative titles and descriptions. Some meaningful keywords will make your photo appear when someone searches for something specific. Here&#039;s just an example, <b><a href="http://www.woophy.com/map#&amp;key=keywords&amp;val=glacier" target="_blank" rel="nofollow">glacier</a></b>. Try out for yourself!<br />
<br />
Please have a look at other Woophy user&#039;s photos! We suggest doing this on the map. You can favorite members and photos that you like. And you can discuss and ask questions by commenting on their photos - and even rate them. Many members appreciate photo critique, but keep it fair and constructive. Don&#039;t feel obliged to answer comments received.<br />
<br />
photo: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=38.60768&amp;lmt=0&amp;lng=44.335213&amp;mag=2.290768&amp;val=rik%20herrygers" target="_blank" rel="nofollow">Rik Herrygers</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>The Ambassadors</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_99924.jpg" alt="" title="" /></p>The Woophy language is English, but for every country there is a contact person, the so called Woophy-Ambassador who will be glad to answer any questions you might have in your native language.<br />
<br />
You can find the Woophy-Ambassador for your country on the <b><a href="http://www.woophy.com/member/?ambassadors" target="_blank" rel="nofollow">Ambassadors page</a></b>. From here you can send him or her an email in your own language.<br />
<br />
photo: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=14.058445&amp;lmt=0&amp;lng=-85.140706&amp;mag=14.668508&amp;val=cande" target="_blank" rel="nofollow">Cande</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Donate</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_82984.jpg" alt="" title="" /></p>Become a supporter of Woophy by buying the Genuine <b><a href="http://www.woophy.com/donate" target="_blank" rel="nofollow">Woophy T-shirt</a></b>. All the money received through the sales of this T-shirt will be invested in Woophy. If you don&#039;t want to buy a T-shirt but would like to support Woophy anyway you can always make a <b><a href="http://www.woophy.com/donate" target="_blank" rel="nofollow">donation</a></b>.<br />
<br />
photo: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=11.214494&amp;lmt=0&amp;lng=51.691361&amp;mag=3.337679&amp;val=Hes%20van%20Huizen" target="_blank" rel="nofollow">Hes van Huizen</a></b></font></td></tr>
<tr><td align="center"><p><a href="http://www.woophy.com"><img src="http://www.woophy.com/images/woophy_symbol.gif" border="0"></a></p></td></tr></table></body></html>