<html><body link="#FE9900" alink="#FE9900" vlink="#FE9900"><table width="439" cellpadding="10" cellspacing="0"><tr><td align="center" style="padding:0;border-bottom:1px dotted #66C029"><p><a href="http://www.woophy.com"><img src="http://www.woophy.com/images/woophy_logo.gif" border="0"></a></p></td></tr><tr><td style="padding:10px 10px;border-bottom:1px dotted #66C029"><b><font size="2" face="georgia,arial,helvetica,sans" color="#003900">Carta de Bienvenida {date}</font></b></td></tr><tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Bienvenido a Woophy</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_371509.jpg" alt="" title="" /></p>Hola {user_name}, gracias por unirte a Woophy. Somos una comunidad de más de 40.000 fotógrafos amateurs dedicada a crear un trabajo artístico, accesible y colectivo que, desde lo visual y de una manera democrática, buscamos crear un portafolio de imágenes de nuestro maravilloso mundo.<br />
<br />
Con la finalidad de ayudarte en el inicio, hemos creado esta pequeña bienvenida con algunos consejos que te ayudarán a disfrutar Woophy. No es necesario que lo leas completamente ahora, pero podrás guardarlo para futuras consultas.<br />
<br />
¿Algunas preguntas? Toma tu tiempo para descubrir todo acerca de Woophy, dale una mirada a Woophy <b><a href="http://www.woophy.com/faq" target="_blank" rel="nofollow">FAQ</a></b> y por favor siéntete libre de contactar en cualquier momento a tu embajador Woophy (ver más abajo) para que te guíe en el inicio. Además, siempre encontrarás alguien dispuesto a ayudar en el <b><a href="http://www.woophy.com/forum" target="_blank" rel="nofollow">forum</a></b>.<br />
<br />
foto: <b><a href="http://www.woophy.com/member/ewest/photos?&amp;order_by=rating" target="_blank" rel="nofollow">ewest</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Consejos prácticos</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_657561.jpg" alt="" title="" /></p>Ahora que ya eres un miembro de Woophy, esperamos que nos muestres tus fotografías y, si tienes varias tomas que juntas cuenten una historia, ¿por qué no crear un <b><a href="http://www.woophy.com/member/?blogs" target="_blank" rel="nofollow">blog</a></b>?<br />
<br />
Muy pronto te darás cuenta que algunos miembros de Woophy han visto tus fotos, las habrán calificado y comentado. Te invitamos a que hagas lo mismo.<br />
<br />
Al hacerlo (en una escala de una a cinco estrellas), ayudas a la comunidad a encontrar de manera más fácil las mejores o las más interesantes tomas.<br />
<br />
Puedes ayudar dejando un comentario constructivo en las fotos. Quizás ésta no sea una tarea fácil, pero toma tu tiempo y comenta lo que te gusta o no te gusta de cada toma. Los comentarios honestos y la crítica constructiva ayudan a que mejoremos nuestras habilidades.<br />
Woophy también cuenta con un <b><a href="http://www.woophy.com/forum" target="_blank" rel="nofollow">forum</a></b> con muchos y variados temas. No dudes en darle una mirada. A través del selector de temas, encontrarás una lista de discusiones en curso en las que puedes participar, o bien, si hay un tema que tú quieras tratar siempre podrás exponerlo a la comunidad.<br />
<br />
foto: <b><a href="http://www.woophy.com/member/Richt/photos?&amp;order_by=rating" target="_blank" rel="nofollow">Richt</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Lo que sí y lo que no.</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_689481.jpg" alt="" title="" /></p>Por favor comparte con nosotros tus fotografías del mundo. Todas las fotos son bienvenidas, especialmente aquellas que nos muestran un lugar, cómo es y cómo se siente. Por favor no alteres demasiado tus tomas digitalmente (un poco de contraste y corrección de color es suficiente), no les agregues grandes sobreexposiciones de texto, (una pequeña referencia de Copyright es suficiente) ni les agregues bordes &quot;opresivos&quot;.<br />
<br />
No está permitido subir anuncios comerciales, pornografía, propaganda política, tomas morbosas o fotos que no sean tuyas, esto es ilegal y, si lo haces, daremos de baja tu cuenta.<br />
<br />
Agrega información a tus fotos, ésta puede ir desde un titulo a una descripción de la toma o algunas palabras clave que le den sentido. Esto ayudara a los demás miembros a encontrar tus fotos cuando busquen fotos por tema o palabra clave. Por ejemplo, prueba a buscar <b><a href="http://www.woophy.com/map#&amp;key=keywords&amp;val=glacier" target="_blank" rel="nofollow">&quot;glacier&quot;</a></b>.<br />
<br />
Echa un vistazo a las fotos de otros miembros. Te sugerimos que lo hagas desde el mapa. Puedes hacer a algunos miembros parte de tus fotógrafos favoritos o bien puedes agregar a tu carpeta de favoritas las tomas que más te gusten. También puedes discutir o hacer preguntas a través de tus comentarios a las fotos de los demás e inclusive calificarlas. La mayoría de los miembros valoran la crítica siempre y cuando ésta sea honesta y constructiva. Por último, no te sientas obligado a responder los comentarios que recibas.<br />
<br />
foto: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=38.60768&amp;lmt=0&amp;lng=44.335213&amp;mag=2.290768&amp;val=rik%20herrygers" target="_blank" rel="nofollow">Rik Herrygers</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Embajadores-Woophy</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_99924.jpg" alt="" title="" /></p>El lenguaje de Woophy es el Inglés, pero cada país tiene un representante y lo llamamos Embajador-Woophy. Contáctalo y con gusto responderá tus preguntas en tu propio idioma.<br />
<br />
Podrás encontrar el Embajador-Woophy de tu país en <b><a href="http://www.woophy.com/member/?ambassadors" target="_blank" rel="nofollow">&quot;Ambassadors Page&quot;</a></b>. Desde allí podrás enviarle un E-mail en tu propio idioma.<br />
<br />
foto: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=14.058445&amp;lmt=0&amp;lng=-85.140706&amp;mag=14.668508&amp;val=cande" target="_blank" rel="nofollow">Cande</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Donate</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_82984.jpg" alt="" title="" /></p>Apoya a Woophy comprando una <b><a href="http://www.woophy.com/donate" target="_blank" rel="nofollow">T-shirt original de Woophy</a></b>. Todo el dinero que se recaude a través de esas ventas será invertido en Woophy. Si no quieres comprar la T-shirt pero quieres apoyar a Woophy, existe la opción de hacer una <b><a href="http://www.woophy.com/donate" target="_blank" rel="nofollow">donación</a></b>.<br />
<br />
foto: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=11.214494&amp;lmt=0&amp;lng=51.691361&amp;mag=3.337679&amp;val=Hes%20van%20Huizen" target="_blank" rel="nofollow">Hes van Huizen</a></b></font></td></tr><tr><td align="center"><p><a href="http://www.woophy.com"><img src="http://www.woophy.com/images/woophy_symbol.gif" border="0"></a></p></td></tr></table></body></html>