<html><body link="#FE9900" alink="#FE9900" vlink="#FE9900"><table width="439" cellpadding="10" cellspacing="0"><tr><td align="center" style="padding:0;border-bottom:1px dotted #66C029"><p><a href="http://www.woophy.com"><img src="http://www.woophy.com/images/woophy_logo.gif" border="0"></a></p></td></tr>
<tr><td style="padding:10px 10px;border-bottom:1px dotted #66C029"><b><font size="2" face="georgia,arial,helvetica,sans" color="#003900">Willkommensbrief {date}</font></b></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Willkommen bei Woophy</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_371509.jpg" alt="" title="" /></p>Hallo {user_name}, wir freuen uns, dass Du dich dafür entschieden hast, Woophy beizutreten, der
freundlichen Gemeinschaft von über 40000 Amateur-Fotografen, die gemeinsam versuchen, eine allgemein zugängliche, visuelle, vielfältige, zeitgemäße, demokratisch verwaltete Datenbank zu schaffen, die unsere bemerkenswerte Welt abbildet.<br />
<br />
Um Dir den Einstieg zu erleichtern, haben wir in diesem Newsletter einige Tipps und Tricks zur besseren Orientierung bei Woophy aufgelistet. Du brauchst nicht alles sofort zu lesen, aber vielleicht kannst Du später die eine oder andere Information nutzen.<br />
Hast Du Fragen? Lass Dir Zeit dabei, alle Funktionen von Woophy zu erkunden.<br />
Werfe einen Blick auf die Woophy <b><a href="http://www.woophy.com/faq" target="_blank" rel="nofollow">FAQ</a></b> und zögere nicht, Deinen Woophy-Botschafter (s.u.) um Rat zu fragen. Außerdem wirst Du im <b><a href="http://www.woophy.com/forum" target="_blank" rel="nofollow">Forum</a></b> immer jemanden finden, der Dir weiterhilft.<br />
<br />
Foto: <b><a href="http://www.woophy.com/member/ewest/photos?&amp;order_by=rating" target="_blank" rel="nofollow">ewest</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Tipps und Tricks</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_657561.jpg" alt="" title="" /></p>Nachdem Du nun Woophy-Mitglied geworden bist, freuen wir uns auf Deine schönsten Fotos.  Wenn Du eine Reihe von Fotos hast, die sich zu einer Geschichte zusammenfügen, warum dann nicht ein <b><a href="http://www.woophy.com/member/?blogs" target="_blank" rel="nofollow">Blog</a></b> schreiben?<br />
Du wirst bald erkennen, dass andere sich Deine Bilder ansehen, sie sogar bewerten und kommentieren. Natürlich kannst Du auch gern die Bilder der anderen Mitglieder  bewerten und kommentieren.<br />
<br />
Durch Deine Bewertung (auf einer Skala von einem bis fünf Sternen) hilfst Du der Gemeinschaft, schnell die besten oder interessantesten Bilder zu finden.<br /> 
Es ist für andere hilfreich, wenn Du einen aussagekräftigen Kommentar zu den Bildern hinterlässt. Das ist nicht immer einfach, aber nimm Dir doch bitte die Zeit und schreib, was Dir an dem Bild gefällt oder missfällt. Die ehrlichen und konstruktiven Kommentare, die Du für Deine Bilder bekommst, können Dir dabei helfen, Deine Fotografie zu verbessern.<br />
<br />
Woophy bietet auch ein Forum mit einer Vielzahl von Themen. Schau doch einfach mal die Threads an, indem Du den Reiter <b><a href="http://www.woophy.com/forum" target="_blank" rel="nofollow">Forum</a></b> anwählst. Dort findest Du eine Auflistung der aktuellen Diskussionen. Wenn Du über ein neues Thema diskutieren möchtest, eröffne einfach Deinen eigenen Thread.<br />
<br />
Foto: <b><a href="http://www.woophy.com/member/Richt/photos?&amp;order_by=rating" target="_blank" rel="nofollow">Richt</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Do&#039;s and don&#039;ts</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_689481.jpg" alt="" title="" /></p>Wir würden uns freuen, wenn Du Deine Eindrücke der Welt mit uns teilst. Alle Arten von Fotos sind willkommen, insbesondere solche, die einen Eindruck eines Ortes vermitteln, d.h. wie es dort aussieht und es sich anfühlt. Bitte verändere Deine Fotos technisch nicht zu sehr (kleine Kontrast- und Farbkorrekturen sind völlig in Ordnung), vermeide bitte riesige Texteinblendungen (eine kleine Copyright-Notiz ist kein Problem) und erdrückende Rahmen.<br />
<br />
Bitte stell keine Werbung, Pornographisches, politische Propaganda, blutrünstige Bilder oder Fotos ein, die nicht Dein Eigentum sind. Dies ist illegal und wir wollen ja unseren fiesen Woophy Account Zerstörer nicht unbedingt aktivieren.<br />
<br />
Die Betrachter Deiner Bilder möchten möglicherweise Näheres über Deine Fotos erfahren! Füge daher doch bitte informative Bildüberschriften und Beschreibungen mit ein. Durch ein paar sinnvolle Stichworte kann Dein Foto besser von jemandem ausfindig gemacht werden, der nach etwas Spezifischem sucht. Hier ein kurzes Beispiel: <b><a href="http://www.woophy.com/map#&amp;key=keywords&amp;val=glacier" target="_blank" rel="nofollow">&quot;glacier&quot;</a></b>. Versuch es doch einmal selbst!<br />
<br />
Bitte schau Dir die Fotos von anderen Woophy-Mitgliedern an! Tu dies am besten mit Hilfe der Karte. Du kannst bestimmte Mitglieder und Fotos auch als Favoriten speichern.<br />
Durch Kommentieren der Fotos kannst Du Diskussionen anregen oder Fragen stellen - und Du kannst die Bilder sogar bewerten. Viele Mitglieder wissen Bildkritik zu schätzen, aber sei bitte fair und konstruktiv. Fühl Dich nicht verpflichtet, auf erhaltene Kommentare zu antworten.<br />
<br />
Foto: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=38.60768&amp;lmt=0&amp;lng=44.335213&amp;mag=2.290768&amp;val=rik%20herrygers" target="_blank" rel="nofollow">Rik Herrygers</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Die Botschafter</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_99924.jpg" alt="" title="" /></p>Die Woophy-Sprache ist Englisch, aber es gibt für jedes Land eine Kontaktperson, den sogenannten Woophy-Botschafter, der Dir gern bei allen aufkommenden Fragen in Deiner Landessprache weiterhilft.<br />
<br />
Du findest den Woophy-Botschafter Deines Landes auf der <b><a href="http://www.woophy.com/member/?ambassadors" target="_blank" rel="nofollow">Ambassador-Seite</a></b>. Von dort aus kannst Du ihm oder ihr auch eine E-Mail in Deiner Muttersprache schicken.<br />
<br />
Foto: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=14.058445&amp;lmt=0&amp;lng=-85.140706&amp;mag=14.668508&amp;val=cande" target="_blank" rel="nofollow">Cande</a></b></font></td></tr>
<tr><td style="padding:20px 10px;border-bottom:1px dotted #66C029" valign="top"><p><font size="3" face="georgia,arial,helvetica,sans" color="#003900"><b>Spenden</b></font></p><font size="2" face="georgia,arial,helvetica,sans" color="#003900"><p><img border="0" src="http://www.woophy.com/images/welcome/welcome_82984.jpg" alt="" title="" /></p>Unterstütze Woophy durch den Kauf eines Original <b><a href="http://www.woophy.com/donate" target="_blank" rel="nofollow">Woophy T-Shirts</a></b>. Alles durch den Verkauf erwirtschaftete Geld wird bei Woophy investiert. Wenn Du kein T-Shirt kaufen möchtest, Woophy aber trotzdem unterstützen willst, kannst Du natürlich mit einer <b><a href="http://www.woophy.com/donate" target="_blank" rel="nofollow">Spende</a></b> helfen.<br />
<br />
Foto: <b><a href="http://www.woophy.com/map#&amp;key=username&amp;lat=11.214494&amp;lmt=0&amp;lng=51.691361&amp;mag=3.337679&amp;val=Hes%20van%20Huizen" target="_blank" rel="nofollow">Hes van Huizen</a></b></font></td></tr>
<tr><td align="center"><p><a href="http://www.woophy.com"><img src="http://www.woophy.com/images/woophy_symbol.gif" border="0"></a></p></td></tr></table></body></html>